"""add_user_token_and_performance_metrics.

Revision ID: 9f8e7d6c5b4a
Revises: 800075668798
Create Date: 2025-11-18 15:52:13.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f8e7d6c5b4a"
down_revision: str | None = "800075668798"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.add_column(
            sa.Column("user_token", sa.BigInteger(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column(
                "time_to_first_token",
                sa.Float(),
                nullable=False,
                server_default="0.0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "tokens_per_second", sa.Float(), nullable=False, server_default="0.0"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource_usage") as batch_op:
        batch_op.drop_column("tokens_per_second")
        batch_op.drop_column("time_to_first_token")
        batch_op.drop_column("user_token")
    # ### end Alembic commands ###
