"""edit_and_star_chat.

Revision ID: d7acba133f2b
Revises: 77c3a2c91298
Create Date: 2025-08-19 14:58:55.846157
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7acba133f2b"
down_revision: str | None = "77c3a2c91298"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chats") as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True).with_variant(sa.Text(), "sqlite"),
                nullable=True,
            ),
        )
        batch_op.add_column(
            sa.Column(
                "starred_at",
                sa.DateTime(timezone=True).with_variant(sa.Text(), "sqlite"),
                nullable=True,
            ),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chats") as batch_op:
        batch_op.drop_column("starred_at")
        batch_op.drop_column("updated_at")
    # ### end Alembic commands ###
