/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function listenIpcElicitationRequest(callback: ((err: Error | null, arg: string) => any)): Promise<void>

export declare function responseElicitation(action: number, content: Record<string, string>): Promise<void>
